version: '3'
services:
  client:
    container_name: client
    build: 
      context: './client'
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    links:
      - server
    depends_on: 
      - server
    ports:
      - "4200:80"

  server:
    container_name: server
    build: 
      context: './server'
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "80:80"
    depends_on:
      - client
      - server